DROP DATABASE IF EXISTS POKEDEX;
CREATE DATABASE IF NOT EXISTS POKEDEX;
USE POKEDEX;
CREATE TABLE POKEMON(
	NUMERO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(25) NOT NULL,
    TIPO INT,
    EVOLUCAO INT,
    CONSTRAINT FK_EVOLUCAO_PKMN FOREIGN KEY (EVOLUCAO) REFERENCES POKEMON(NUMERO)
);

CREATE TABLE TIPO(
	ID INT,
    NOME VARCHAR(20),
    PRIMARY KEY (ID)
);

ALTER TABLE POKEMON ADD CONSTRAINT FK_TIPO_PKMN FOREIGN KEY (TIPO) REFERENCES TIPO(ID);

CREATE TABLE HABILIDADE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    TIPO INT NOT NULL,
    DANO FLOAT NOT NULL,
    CONSTRAINT FK_TIPO_PWR FOREIGN KEY (ID) REFERENCES TIPO(ID)
);


INSERT INTO TIPO VALUES(1, 'NORMAL');
INSERT INTO TIPO VALUES(2, 'GRAMA');

INSERT INTO POKEMON VALUES (1, "BULBASAUR", 2, NULL);
